jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build

      - name: List build artifacts
        run: ls -l build/libs

      - name: Build Docker image
        run: docker build -t nanajanashia/demo-app:latest .

